import FWCore.ParameterSet.Config as cms

variations = cms.VPSet(
    cms.PSet(
        label        = cms.string("eigenvector1plus"),
        outputDir    = cms.string("output/ev_1p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5001"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector1minus"),
        outputDir    = cms.string("output/ev_1m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5002"),
    ),
    cms.PSet(
        label        = cms.string("nominal"),
        outputDir    = cms.string("output/nominal"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(True),
        pdfWeightId  = cms.string("5000"),
    ),
)
