import FWCore.ParameterSet.Config as cms

variations = cms.VPSet(
    cms.PSet(
        label        = cms.string("acceptance"),
        outputDir    = cms.string("output/acceptance"),
        electronSource = cms.string("Gen"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(True),
        pdfWeightId  = cms.string("5000"),
    ),
    cms.PSet(
        label        = cms.string("acceptance_a"),
        outputDir    = cms.string("output/region_a"),
        electronSource = cms.string("Gen"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        region       = cms.uint32(1),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(True),
        pdfWeightId  = cms.string("5000"),
    ),
    cms.PSet(
        label        = cms.string("acceptance_b"),
        outputDir    = cms.string("output/region_b"),
        electronSource = cms.string("Gen"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        region       = cms.uint32(2),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(True),
        pdfWeightId  = cms.string("5000"),
    ),
    #cms.PSet(
    #    label        = cms.string("low_qT_high_HT"),
    #    outputDir    = cms.string("output/low_qT_high_HT"),
    #    electronSource = cms.string("Gen"),
    #    minPte1      = cms.double(25.0),
    #    minPte2      = cms.double(15.0),
    #    maxEta       = cms.double(2.5),
    #    minEta       = cms.double(0.0),
    #    maxJetEta    = cms.double(5.0),
    #    minHT        = cms.double(150.0),
    #    maxqT        = cms.double(10.0),
    #    notInGap     = cms.bool(True),
    #    useNominalOnly = cms.bool(True),
    #    pdfWeightId  = cms.string("5000"),
    #),
    #cms.PSet(
    #    label        = cms.string("smeared"),
    #    outputDir    = cms.string("output/smeared"),
    #    electronSource = cms.string("Smeared"),
    #    minPte1      = cms.double(25.0),
    #    minPte2      = cms.double(15.0),
    #    maxEta       = cms.double(2.5),
    #    minEta       = cms.double(0.0),
    #    maxJetEta    = cms.double(5.0),
    #    minHT        = cms.double(0.0),
    #    maxqT        = cms.double(1000000.0),
    #    notInGap     = cms.bool(True),
    #    useNominalOnly = cms.bool(True),
    #    pdfWeightId  = cms.string("5000"),
    #),
)
