import FWCore.ParameterSet.Config as cms

variations = cms.VPSet(
    cms.PSet(
        label        = cms.string("eigenvector1plus"),
        outputDir    = cms.string("output/ev_1p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5001"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector1minus"),
        outputDir    = cms.string("output/ev_1m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5002"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector2plus"),
        outputDir    = cms.string("output/ev_2p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5003"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector2minus"),
        outputDir    = cms.string("output/ev_2m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5004"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector3plus"),
        outputDir    = cms.string("output/ev_3p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5005"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector3minus"),
        outputDir    = cms.string("output/ev_3m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5006"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector4plus"),
        outputDir    = cms.string("output/ev_4p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5007"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector4minus"),
        outputDir    = cms.string("output/ev_4m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5008"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector5plus"),
        outputDir    = cms.string("output/ev_5p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5009"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector5minus"),
        outputDir    = cms.string("output/ev_5m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5010"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector6plus"),
        outputDir    = cms.string("output/ev_6p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5011"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector6minus"),
        outputDir    = cms.string("output/ev_6m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5012"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector7plus"),
        outputDir    = cms.string("output/ev_7p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5013"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector7minus"),
        outputDir    = cms.string("output/ev_7m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5014"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector8plus"),
        outputDir    = cms.string("output/ev_8p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5015"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector8minus"),
        outputDir    = cms.string("output/ev_8m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5016"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector9plus"),
        outputDir    = cms.string("output/ev_9p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5017"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector9minus"),
        outputDir    = cms.string("output/ev_9m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5018"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector10plus"),
        outputDir    = cms.string("output/ev_10p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5019"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector10minus"),
        outputDir    = cms.string("output/ev_10m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5020"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector11plus"),
        outputDir    = cms.string("output/ev_11p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5021"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector11minus"),
        outputDir    = cms.string("output/ev_11m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5022"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector12plus"),
        outputDir    = cms.string("output/ev_12p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5023"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector12minus"),
        outputDir    = cms.string("output/ev_12m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5024"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector13plus"),
        outputDir    = cms.string("output/ev_13p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5025"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector13minus"),
        outputDir    = cms.string("output/ev_13m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5026"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector14plus"),
        outputDir    = cms.string("output/ev_14p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5027"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector14minus"),
        outputDir    = cms.string("output/ev_14m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5028"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector15plus"),
        outputDir    = cms.string("output/ev_15p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5029"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector15minus"),
        outputDir    = cms.string("output/ev_15m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5030"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector16plus"),
        outputDir    = cms.string("output/ev_16p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5031"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector16minus"),
        outputDir    = cms.string("output/ev_16m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5032"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector17plus"),
        outputDir    = cms.string("output/ev_17p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5033"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector17minus"),
        outputDir    = cms.string("output/ev_17m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5034"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector18plus"),
        outputDir    = cms.string("output/ev_18p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5035"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector18minus"),
        outputDir    = cms.string("output/ev_18m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5036"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector19plus"),
        outputDir    = cms.string("output/ev_19p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5037"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector19minus"),
        outputDir    = cms.string("output/ev_19m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5038"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector20plus"),
        outputDir    = cms.string("output/ev_20p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5039"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector20minus"),
        outputDir    = cms.string("output/ev_20m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5040"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector21plus"),
        outputDir    = cms.string("output/ev_21p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5041"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector21minus"),
        outputDir    = cms.string("output/ev_21m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5042"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector22plus"),
        outputDir    = cms.string("output/ev_22p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5043"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector22minus"),
        outputDir    = cms.string("output/ev_22m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5044"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector23plus"),
        outputDir    = cms.string("output/ev_23p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5045"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector23minus"),
        outputDir    = cms.string("output/ev_23m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5046"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector24plus"),
        outputDir    = cms.string("output/ev_24p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5047"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector24minus"),
        outputDir    = cms.string("output/ev_24m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5048"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector25plus"),
        outputDir    = cms.string("output/ev_25p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5049"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector25minus"),
        outputDir    = cms.string("output/ev_25m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5050"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector26plus"),
        outputDir    = cms.string("output/ev_26p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5051"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector26minus"),
        outputDir    = cms.string("output/ev_26m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5052"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector27plus"),
        outputDir    = cms.string("output/ev_27p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5053"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector27minus"),
        outputDir    = cms.string("output/ev_27m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5054"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector28plus"),
        outputDir    = cms.string("output/ev_28p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5055"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector28minus"),
        outputDir    = cms.string("output/ev_28m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5056"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector29plus"),
        outputDir    = cms.string("output/ev_29p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5057"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector29minus"),
        outputDir    = cms.string("output/ev_29m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5058"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector30plus"),
        outputDir    = cms.string("output/ev_30p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5059"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector30minus"),
        outputDir    = cms.string("output/ev_30m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5060"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector31plus"),
        outputDir    = cms.string("output/ev_31p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5061"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector31minus"),
        outputDir    = cms.string("output/ev_31m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5062"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector32plus"),
        outputDir    = cms.string("output/ev_32p"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5063"),
    ),
    cms.PSet(
        label        = cms.string("eigenvector32minus"),
        outputDir    = cms.string("output/ev_32m"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(False),
        pdfWeightId  = cms.string("5064"),
    ),
    cms.PSet(
        label        = cms.string("nominal"),
        outputDir    = cms.string("output/nominal"),
        electronSource = cms.string("Dressed"),
        minPte1      = cms.double(25.0),
        minPte2      = cms.double(15.0),
        maxEta       = cms.double(2.5),
        minEta       = cms.double(0.0),
        minJetPt     = cms.double(20.0),
        maxJetEta    = cms.double(5.0),
        minHT        = cms.double(0.0),
        maxqT        = cms.double(1000000.0),
        notInGap     = cms.bool(True),
        useNominalOnly = cms.bool(True),
        pdfWeightId  = cms.string("5000"),
    ),
)
